name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "569f2363dd424502989be1641d7f3c5f" }
]

[triggers]
crons = [ ]
